WITH TMP AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
       OR END_DATE = '2022-10-16'
)


SELECT CAR_ID, '대여중' AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID FROM TMP)
UNION
SELECT CAR_ID, '대여 가능' AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID NOT IN (SELECT CAR_ID FROM TMP)
ORDER BY CAR_ID DESC;