SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT F
WHERE PRICE = (SELECT MAX(PRICE)
              FROM FOOD_PRODUCT
              WHERE CATEGORY = F.CATEGORY)
    AND CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY PRICE DESC;